services:
  app:
    build:
      .
      #context: .. # Build context is the parent directory (churn-prediction-app/)
      #dockerfile: docker/Dockerfile # Location of the Dockerfile inside the 'docker/' folder

    container_name: data_science_app
    ports:
      - "49152:8888" # Jupyter Notebook
      - "49153:8501" # Streamlit
    volumes:
      - ..:/app
    environment:
      - JUPYTER_TOKEN=passw0rd
    command: >
      sh -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root &
             streamlit run app.py --server.port 8501 --server.address 0.0.0.0"
